Repository BoboTiG/ebook-reader-dict, pull requests merged in 2020-12, with the labels that each got.

#414 fix #413: [EN] Support template aliases: pre, suf, com, blend of
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#408 [FR] Support the 'Citation' template (closes #365)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#416 fix #415: [EN] Support all 'form-of' templates
  scripts/lang/en/__init__.py
  scripts/lang/en/form_of.py
  tests/test_en.py
Labels: enhancement, locale:English

#418 fix #415: [EN] Support 'named-after' template
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#423 fix #422: [EN] add shortcuts of supported templates
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#421 fix #420: [EN] bad render of 'blend of'
  scripts/lang/en/__init__.py
Labels: bug, locale:English

#432 [EN] Support '...' and 'nb...' templates (closes #431)
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#440 fix #437: [EN] Support 'nuclide' and 'frac' templates
  scripts/lang/en/__init__.py
Labels: enhancement, locale:Français

#442 fix #441: [EN] Crash on coin/coinage template
  scripts/lang/en/__init__.py
Labels: bug, locale:English

#443 fix #433: [FR] Ignore 'Article' and 'périodique' templates
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#434 fix #424: [EN] Support 'SI-Unit' template and friends
  scripts/lang/en/__init__.py
  scripts/lang/en/si_unit.py
Labels: enhancement, locale:English

#444 fix #438: [EN] Support 'Latn-def' template
  scripts/lang/en/__init__.py
  tests/test_en.py
Labels: enhancement, locale:English

#445 fix #439: [EN] Support all English form-of templates
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#452 [FR] Support the 'nom-déposé' template (closes #450)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#453 [FR] Support 'note-gentilé' template (closes #449)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#454 [FR] Support 'p-us' template (closes #451)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#461 Issue #459: Start locale refactoring
  scripts/lang/fr/__init__.py
  scripts/lang/fr/template_handlers.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#463 Issue #459: refactor ES locale
  scripts/lang/es/__init__.py
  scripts/lang/es/template_handlers.py
Labels: enhancement, locale:Español

#466 Project refactoring: download step (related to #458)
  README.md
  check.sh
  requirements.txt
  setup.cfg
  tests/test_main_download.py
  wikidict/__init__.py
  wikidict/__main__.py
  wikidict/constants.py
  wikidict/download.py
Labels: enhancement

#467 fix #457: [FR] Support 'x10' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#470 --get-word: Strip &thinsp; HTML character
  wikidict/get_word.py
Labels: bug

#471 --parse: Small refactoring
  wikidict/parse.py
Labels: enhancement

#472 --render: Small refactoring
  wikidict/render.py
Labels: enhancement

#474 --parse: Do not parse again if it was already done
  wikidict/__main__.py
  wikidict/parse.py
Labels: enhancement

#468 Fix #456: [FR] Handle ar-mot and ar-terme
  scripts/lang/fr/__init__.py
  scripts/lang/fr/arabiser.py
Labels: enhancement, locale:Français

#479 Finish the refactoring + more tests coverage
  .github/workflows/auto-updates.yml
  .github/workflows/quality.yml
  .github/workflows/tests.yml
  .gitignore
  check.sh
  scripts/__init__.py
  scripts/__main__.py
  scripts/constants.py
  scripts/convert.py
  scripts/get.py
  setup.cfg
  tests/test_0_download.py
  tests/test_0_get.py
  tests/test_1_parse.py
  tests/test_2_render.py
  tests/test_3_convert.py
  tests/test_3_main.py
  tests/test_4_find_templates.py
  tests/test_4_get_word.py
  tests/test_4_upload.py
  tests/test_ca.py
  tests/test_en.py
  tests/test_es.py
  tests/test_fr.py
  tests/test_pt.py
  tests/test_sv.py
  wikidict/__main__.py
  wikidict/convert.py
  wikidict/download.py
  wikidict/find_templates.py
  wikidict/get_word.py
  wikidict/lang/__init__.py
  wikidict/lang/ca/__init__.py
  wikidict/lang/ca/langs.py
  wikidict/lang/defaults.py
  wikidict/lang/en/__init__.py
  wikidict/lang/en/form_of.py
  wikidict/lang/en/langs.py
  wikidict/lang/en/places.py
  wikidict/lang/en/si_unit.py
  wikidict/lang/en/template_handlers.py
  wikidict/lang/es/__init__.py
  wikidict/lang/es/langs.py
  wikidict/lang/es/template_handlers.py
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/arabiser.py
  wikidict/lang/fr/domain_templates.py
  wikidict/lang/fr/langs.py
  wikidict/lang/fr/template_handlers.py
  wikidict/lang/pt/__init__.py
  wikidict/lang/pt/langs.py
  wikidict/lang/sv.py
  wikidict/parse.py
  wikidict/render.py
  wikidict/stubs.py
  wikidict/transliterator.py
  wikidict/upload.py
  wikidict/user_functions.py
  wikidict/utils.py
Labels: enhancement

#482 Fix StarDict file creation
  .github/workflows/auto-updates.yml
Labels: bug

#495 fix #448: [EN] Support 'historical given name' template
  wikidict/lang/en/template_handlers.py
Labels: enhancement, locale:English

#496 fix #493: [PT] Add support for the 'gramática' template
  wikidict/lang/pt/__init__.py
  wikidict/lang/pt/gramatica.py
Labels: enhancement, locale:Português
