Repository BoboTiG/ebook-reader-dict, pull requests merged in 2020-11, with the labels that each got.

#181 fix #178: [CA] Handle the 'etim-s' template
  scripts/lang/ca.py
  tests/test_ca.py
Labels: locale:Catalan

#183 fix #179: [CA] Handle the 'etim-lang' template
  scripts/lang/__init__.py
  scripts/lang/ca/__init__.py
  scripts/lang/ca/langs.py
Labels: locale:Catalan

#184 fix #136: [CA] Add etymology
  scripts/get.py
  scripts/lang/__init__.py
  scripts/lang/ca/__init__.py
  tests/test_ca.py
Labels: enhancement, locale:Catalan

#189 [CA] Improve the pronunciation regex (closes #188)
  scripts/lang/ca/__init__.py
  tests/data/ca/PMF.wiki
  tests/data/ca/el.wiki
Labels: enhancement, locale:Catalan

#186 Only add a fake etymology section for CA (related to #136)
  scripts/get.py
Labels: enhancement, locale:Catalan

#190 fix #187: [CA] Fix handling of the 'etim-lang' template
  scripts/lang/ca/__init__.py
  tests/test_ca.py
Labels: bug, locale:Catalan

#191 fix #167: [FR] Redirect conjuged verbs to their infinitive form
  scripts/constants.py
  scripts/convert.py
  scripts/get.py
  scripts/lang/fr/__init__.py
  scripts/stubs.py
  tests/data/fr/colligeait.wiki
  tests/data/fr/colliger.wiki
  tests/test_0_get.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#194 Normalize variants (#167)
  scripts/convert.py
Labels: enhancement

#204 fix#203: fr-verbe-flexion template for avais
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#205 [FR] Better handle the 'date' template (closes #196)
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#211 fix #210: [FR] Handle verb forms with two first letters different fro…
  scripts/convert.py
  tests/data/fr/geler.wiki
  tests/data/fr/gèlent.wiki
  tests/test_1_convert.py
Labels: enhancement, locale:Français

#213 fix #212: [FR] Fix for keywords-only 'fr-verbe-flexion' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: bug, locale:Français

#218 Support multiple pronunciations
  scripts/convert.py
  scripts/get.py
  scripts/stubs.py
  scripts/utils.py
  tests/test_0_get.py
  tests/test_ca.py
  tests/test_en.py
  tests/test_es.py
  tests/test_fr.py
  tests/test_pt.py
  tests/test_sv.py
Labels: enhancement

#223 fix #208: [FR] Redirect plural of a noun to singular or to a verb if …
  scripts/constants.py
  scripts/convert.py
  tests/data/fr/minute.wiki
  tests/data/fr/minuter.wiki
  tests/data/fr/minutes.wiki
  tests/test_1_convert.py
Labels: enhancement, locale:Français

#228 [FR] Use non-breakable spaces instead of simple spaces with quotes (f…
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#230 fix #229: [FR] Support W template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#233 fix #232: [FR] support l template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#246 fix #237: [FR] Sub sub list not handled correctly
  scripts/convert.py
  scripts/get.py
  scripts/stubs.py
  tests/test_0_get.py
  tests/test_fr.py
Labels: bug, locale:Français

#248 [FR] Handle empty date template (closes #240)
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#252 fix #239, #251 : Handle 'agglutination' and 'univerbation' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#256 [FR] Handle the 'phon' template (closes #255)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#259 fix #258: [FR] Handle 'syncope' et 'parataxe'
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#225 Handle the <math> HTML tag (closes #54)
  .github/workflows/auto-updates.yml
  .github/workflows/tests.yml
  requirements.txt
  scripts/constants.py
  scripts/utils.py
  tests/data/en/on.wiki
  tests/test_en.py
Labels: enhancement

#266 Simplify transform()
  scripts/lang/__init__.py
  scripts/lang/defaults.py
  scripts/lang/fr/__init__.py
  scripts/utils.py
Labels: enhancement

#265 [FR] Support the 'Variante ortho de' template (capital V...) (closes …
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#263 fix #254: [FR] Handle 'Unité' template (capital U...)
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#267 fix #250: [FR] handle 'supplétion' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#269 fix #268: [FR] Handle 'dénominal de' and 'déverbial de' templates
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#264 Ease tracking of unsupported templates
  .github/workflows/auto-updates.yml
  scripts/utils.py
Labels: enhancement

#271 fix #270: [FR] Handle 'déglutination' Template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#275 fix #274: [FR] handle détroit template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#278 fix #277: [FR] Handle 'Variante de' (Capital V...)
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#276 [FR] Handle the 'zh-lien' template (closes #273)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#282 [FR] Support the 'équiv-pour' template (closes #280)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#284 fix #283: [FR] Handle 'volley' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#281 fix #279: [FR] Handle 'diminutif' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#287 [FR] Handle 'acronyme' template (closes #285)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#291 [FR] Fix 'acronyme' handling
  scripts/lang/fr/__init__.py
Labels: bug, locale:Français

#288 [FR] Fix 'date' handling with question mark (fixes #286)
  scripts/lang/fr/__init__.py
Labels: bug, locale:Français

#290 fix #289: [FR] Handle 'reverlanisation' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#292 fix #272: [FR] Handle 'LienRouge' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#296 fix #295: [FR] Handle 'trad-' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#298 fix #297: [FR] Add support for 'Modèle de temporalité'
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#294 fix #293: [FR] handle 'cours d'eau' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#301 fix #300: [FR] Handle 'incise' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#302 fix #299: [FR] Handle 'formule chimique' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#304 Log only once a missing template
  scripts/utils.py
Labels: enhancement

#305 [FR] Clean-up last_template_handler()
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#316 fix #306: [FR] Handle the 'familier' italic template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#318 fix #307: [FR] Handle the 'argot' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#319 fix #312: [FR] Handle the 'dérision' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#317 [FR] Ignore the '?' template (closes #303)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#315 [FR] Ignore the 'Ouvrage' template (closes #313)
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#314 [FR] Handle the 'régionalisme' template (closes #309)
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#322 fix #310: [FR] Support the 'la-verb' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#321 Add support for the 'transliterator' template (closes #308)
  scripts/lang/ca/__init__.py
  scripts/lang/defaults.py
  scripts/lang/en/__init__.py
  scripts/lang/es/__init__.py
  scripts/lang/fr/__init__.py
  scripts/lang/pt/__init__.py
  scripts/transliterator.py
  scripts/utils.py
Labels: enhancement

#325 fix #324: [FR] Support 'wd' template
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#336 fix #335: [FR] Support 'locutions latines' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#338 fix #337: [FR] Incorrect rendering of cf with more than 2 parts
  scripts/lang/fr/__init__.py
  scripts/user_functions.py
Labels: enhancement, locale:Français

#340 fix #339: [FR] support 'Légifrance' template
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#346 fix #344: [EN] Add list of language families to langs.py
  scripts/lang/en/langs.py
Labels: enhancement, locale:Français

#348 [EN] Clean-up last_template_handler()
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#351 [EN] Enhance support for 'm' and 'l' templates (closes #347)
  scripts/lang/en/__init__.py
  scripts/transliterator.py
  tests/data/en/us.wiki
  tests/data/fr/corps portant.wiki
  tests/test_en.py
Labels: enhancement, locale:English

#369 [FR] Ignore '*', 'Accord des couleurs' and ibid' templates
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#370 [FR] Support several other templates
  scripts/lang/fr/__init__.py
  tests/test_fr.py
Labels: enhancement, locale:Français

#371 [FR] Support 'note-fr-féminin-homme' and 'note-fr-masculin-femme' tem…
  scripts/lang/fr/__init__.py
Labels: enhancement, locale:Français

#374 Add support for several magic words (closes #356)
  scripts/utils.py
Labels: enhancement

#375 fix #353: [EN] Handle the 'doublet' template
  scripts/lang/en/__init__.py
  tests/test_en.py
Labels: enhancement, locale:English

#378 Clean-up <<foo/bar>> wikicode (closes #349)
  scripts/utils.py
Labels: enhancement

#381 fix #380: handle q template, improve qualifier and qual templates
  scripts/lang/en/__init__.py
  tests/test_en.py
Labels: enhancement, locale:English

#390 start work on #379: support of place template
  scripts/get.py
  scripts/lang/en/__init__.py
  scripts/lang/en/places.py
Labels: enhancement, locale:English

#393 fix misc. errors for english
  .github/workflows/tests.yml
  scripts/lang/en/__init__.py
  scripts/user_functions.py
Labels: enhancement, locale:English

#398 fix #392: [EN] Support noncog/noncognate template
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#400 fix #395: [EN] Ignore multiple templates for english
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English

#401 Improve handling of 'place' template
  scripts/lang/en/__init__.py
  scripts/lang/en/places.py
Labels: enhancement, locale:English

#404 Split the work done by clean into 2 specific functions
  html/scripts/user_functions.html
  scripts/get.py
  scripts/user_functions.py
  scripts/utils.py
  tests/test_ca.py
  tests/test_en.py
  tests/test_es.py
  tests/test_fr.py
  tests/test_pt.py
  tests/test_sv.py
Labels: enhancement

#411 fix #410: [EN] Support 'given name' template
  scripts/lang/en/__init__.py
Labels: enhancement, locale:English
