Repository BoboTiG/ebook-reader-dict, pull requests merged in 2021-01, with the labels that each got.

#505 fix #503: [FR] Ignore the 'lien-ancre-étym' template
  wikidict/lang/fr/__init__.py
Labels: enhancement, locale:Français

#506 fix #504: [FR] Fix handling of the 'abréviation' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: bug, locale:Français

#509 fix #507: Add scripts to auto-update specific data
  check.sh
  requirements.txt
  scripts/__init__.py
  scripts/__main__.py
  scripts/ca-langs.py
  scripts/en-form-of.py
  scripts/en-langs.py
  scripts/en-places.py
  scripts/es-langs.py
  scripts/fr-domain-templates.py
  scripts/fr-langs.py
  scripts/pt-gramatica.py
  scripts/pt-langs.py
Labels: enhancement

#526 fix #513: [EN] Fix handling of the 'named-after' template
  wikidict/lang/en/template_handlers.py
Labels: bug, locale:English

#527 [CA] Ignore 'format-conj', 'categoritza' and 'catllengua' templates
  wikidict/lang/ca/__init__.py
Labels: locale:Catalan

#528 fix #522: [CA] Handle the 'pron' template
  tests/test_ca.py
  wikidict/lang/ca/__init__.py
Labels: locale:Catalan

#529 fix #521: [CA] Handle the 'trad' template
  wikidict/lang/ca/__init__.py
Labels: locale:Catalan

#530 fix #516: [CA] Handle the 'doblet' template
  tests/test_ca.py
  wikidict/lang/ca/__init__.py
Labels: locale:Catalan

#525 fix #447: [EN] Support BCE, circa and other Dating templates
  tests/test_en.py
  wikidict/lang/en/__init__.py
  wikidict/lang/en/template_handlers.py
Labels: locale:English

#531 [EN] Remove problematic 'on' test
  tests/data/en/on.wiki
  tests/test_en.py
Labels: locale:English

#532 fix #501: [FR] Add support for régions
  scripts/__main__.py
  scripts/fr-regions.py
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/regions.py
Labels: locale:Français

#533 fix #501: Improve aliases retrieval
  scripts/fr-regions.py
  wikidict/lang/fr/regions.py
Labels: locale:Français

#538 fix #536: [FR] Better support of 'lien' template
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#540 fix #539: [FR] Better support of 'étyl' template
  tests/test_fr.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#550 fix #547: [PT] Better handling of the 'llietimo' template
  tests/test_pt.py
  wikidict/lang/pt/__init__.py
Labels: locale:Português

#552 fix #551: [PT] Better handling of the 'etimo' template
  wikidict/lang/pt/__init__.py
Labels: locale:Português

#556 fix #544: [EN] Improve handling of CDP 'place' template
  wikidict/lang/en/template_handlers.py
Labels: locale:English

#557 fix #548: [ES] Fix handling of the 'etimología' template
  wikidict/lang/es/template_handlers.py
Labels: locale:Español

#561 fix #560: [FR] Review handling of the 'siècle2' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#563 fix #559: [FR] Empty 'abréviation' should be around parenthesis
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#564 fix #558: [FR] Better handling of the 'étyl' template
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#569 fix #568: Fix handling of imbricated templates 'w' -> 'pc'
  wikidict/lang/defaults.py
  wikidict/utils.py
Labels: bug, locale:Français

#571 fix #343: [FR] Add support for the 'Deva' template
  tests/test_fr.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#566 fix #554: [PT] Add a script to fetch 'escopos'
  scripts/__main__.py
  scripts/pt-escopo.py
  tests/test_pt.py
  wikidict/lang/pt/__init__.py
  wikidict/lang/pt/escopos.py
  wikidict/user_functions.py
Labels: locale:Português

#574 fix #573: [FR] tweak handling of 'nom w pc'
  tests/test_fr.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#595 fix #594: [PT] Words outside the 'escopos' list should not be lowercased
  tests/test_pt.py
  wikidict/lang/pt/__init__.py
  wikidict/user_functions.py
Labels: locale:Português

#597 fix #596: [PT] Add support for country templates
  wikidict/lang/pt/__init__.py
Labels: locale:Português

#599 fix #598: [PR] 'escopoCat' template should make use of the 'escopos' …
  tests/test_pt.py
  wikidict/lang/pt/__init__.py
Labels: locale:Português

#605 fix #588: [ES] [[Categoría]] shouldn't be printed
  wikidict/lang/__init__.py
Labels: locale:Español

#606 fix #589: [ES] Better support of 'superlativo'
  tests/test_es.py
  wikidict/lang/es/__init__.py
  wikidict/lang/es/template_handlers.py
Labels: locale:Español

#607 fix #591: [ES] Handle 'etim' template
  wikidict/lang/es/__init__.py
Labels: locale:Español

#608 fix #593: [ES] Support {{etimología|incierta}}
  wikidict/lang/es/template_handlers.py
Labels: locale:Español

#610 fix #592: [FR] Review output of 'couleur' template
  tests/test_fr.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#617 fix #572: [FR] Tweak handling of the 'composé de' template
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#621 fix #620: [FR] Improve handling of 'siècle' template
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#625 fix #624: [FR] Improve 'Composé de' template for empty param
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#628 fix #627: [FR] Change dash in 'siècle' template
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#629 fix #626: [FR] improve support of 'aphérèse' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#631 fix #630: [FR] mix of italic and bold and apostrophe
  wikidict/lang/fr/__init__.py
  wikidict/utils.py
Labels: locale:Français

#636 fix #632: [FR] Improve support of 'apocope' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#645 fix #642: [FR] Add missing 'latin archaïque' and other latins to langs
  wikidict/lang/fr/langs.py
Labels: locale:Français

#651 fix #638: [FR] Better support for 'WP' template
  tests/test_fr.py
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#658 fix #657: [EN] Add support for the 'glossary' template
  tests/test_en.py
  wikidict/lang/en/__init__.py
Labels: locale:English
