Repository BoboTiG/ebook-reader-dict, pull requests merged in 2021-02, with the labels that each got.

#665 fix #662: [FR] Better support for 'c', 'f', 'm', 'mf' and 'n' templates and their long form
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#664 fix #656: [EN] Handle empty parts of the 'suffix' template
  wikidict/lang/en/template_handlers.py
Labels: locale:English

#682 fix #678: [FR] 'f=o' in 'composé de' template
  wikidict/check_word.py
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#684 fix #683: [FR] Better support for 'siècle' template with I
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#692 fix #690: [FR] 'abreviation' template doesn't have a m option despite doc
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#686 fix #685: check-word with if word contains subdefinitions
  tests/test_4_check_word.py
  wikidict/check_word.py
Labels: bug

#688 fix #679: [FR] Support 'R:TLFi' template
  wikidict/check_word.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#693 Revert "fix #679: [FR] Support 'R:TLFi' template"
  wikidict/check_word.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#696 fix #679: [FR] Support 'R:TLFi' template
  wikidict/lang/fr/__init__.py
  wikidict/utils.py
Labels: locale:Français

#700 fix #694: [FR] Support m option in 'antonomase' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#702 fix #701: [FR] Support options of 'variante orthographique de' template
  tests/test_fr.py
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#705 fix #704: [FR] check-word should ignore 'sur Wikispecies' text
  tests/test_4_check_word.py
  wikidict/check_word.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#707 fix #706: [FR] Improve 'siècle' template with punctuation
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#710 fix #708: [FR] check-word crash on 'wsp' template
  wikidict/check_word.py
Labels: bug, locale:Français

#711 fix #709: [FR] Handle 'ar-ab' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#714 fix #713: [FR] crash on 'ar' template
  wikidict/lang/fr/__init__.py
Labels: bug, locale:Français

#715 fix #712: [FR] handle 'attention' template consistenly and support in check-word
  tests/test_4_check_word.py
  wikidict/check_word.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#720 misc. fixes
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#721 fix #719: [FR] Handle 'code langue' and 'nom langue' templates
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#724 fix #723: Error in handling template directly surrounded by link
  wikidict/utils.py
Labels: bug

#728 fix #718: [FR] Improve 'sigle' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: locale:Français

#732 misc. fixes and more test coverage
  tests/test_4_check_word.py
  wikidict/check_word.py
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
Labels: bug, locale:Français

#734 fix #727: [FR] Support 'registre' template
  tests/test_fr.py
  wikidict/lang/fr/__init__.py
Labels: locale:Français

#737 fix #726: [FR] Improve support for 'unité' template
  wikidict/lang/fr/__init__.py
  wikidict/lang/fr/template_handlers.py
  wikidict/user_functions.py
Labels: locale:Français
